name: CI

on:
  pull_request:

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ruby-version: [3.0, 3.1, 3.2, 'ruby-head']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # 'bundle install' and cache

      - name: Run ${{ matrix.os }} tests
        run: bundle install
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
      - name: Run rubocop
        run: bundle install
        run: bundle exec rubocop
